name = "startkit-next"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION = "20"
BUILD_ENV = "production"
CLOUDFLARE_ACCOUNT_ID = "017b203cbba70f10d4c0be86af2419a7" # Your account id

[[d1_databases]]
binding = "DB"
database_name = "startkit-next-d1"
database_id = "aafb87c5-0776-4a0f-9f5e-7936dab4f5f7"
migrations_dir = "drizzle/migrations"

[env.preview.vars]
NODE_VERSION = "20"
BUILD_ENV = "preview"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "startkit-next-d1-previe"
database_id = "fd96c2ac-b502-4f8f-9e0a-215e08272c75"
migrations_dir = "drizzle/migrations"
